<a href="https://colab.research.google.com/github/himantu/Bank-Management-System-main/blob/main/tensor_GPU_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [6]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.9623, 0.1092, 0.7235],
        [0.5366, 0.8981, 0.2692]], device='cuda:0')

In [9]:
# moving an exiting tenser to GPU
a = torch.rand(2,3)
a

tensor([[0.4291, 0.1053, 0.0946],
        [0.8318, 0.7525, 0.5289]])

In [11]:
b = a.to(device)

In [12]:
b+5

tensor([[5.4291, 5.1053, 5.0946],
        [5.8318, 5.7525, 5.5289]], device='cuda:0')

In [14]:
# reshaping tensors

a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [16]:
# flatten
a.flatten()


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
b  = torch.rand(2,3,4)
b

tensor([[[0.2457, 0.7352, 0.7934, 0.3189],
         [0.3929, 0.1800, 0.3000, 0.8655],
         [0.0094, 0.2280, 0.9811, 0.0725]],

        [[0.0414, 0.3190, 0.5592, 0.4422],
         [0.4837, 0.6304, 0.8087, 0.2200],
         [0.5561, 0.5308, 0.2335, 0.0981]]])

In [19]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [22]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [23]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

In [24]:
import numpy as np

In [26]:
a =torch.tensor([1,2,3])

In [27]:
a

tensor([1, 2, 3])

In [28]:
b = a.numpy()
b

array([1, 2, 3])

In [29]:
type(b)

numpy.ndarray

In [30]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [31]:
torch.from_numpy(c)

tensor([1, 2, 3])